use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

use super::browser::{BrowserEngine, ProxyConfig};

// ─── Fingerprint Configuration ─────────────────────────────────────

/// Fingerprint settings for a browser profile.
/// These control what identity the browser presents to websites.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct FingerprintConfig {
    /// Target OS for fingerprint (e.g., "windows", "macos", "linux")
    #[serde(default)]
    pub os: Option<String>,

    /// Custom user agent string
    #[serde(default)]
    pub user_agent: Option<String>,

    /// Screen resolution [width, height]
    #[serde(default)]
    pub screen: Option<[u32; 2]>,

    /// WebGL vendor string (e.g., "Google Inc. (NVIDIA)")
    #[serde(default)]
    pub webgl_vendor: Option<String>,

    /// WebGL renderer string (e.g., "ANGLE (NVIDIA GeForce RTX 3080)")
    #[serde(default)]
    pub webgl_renderer: Option<String>,

    /// Timezone (e.g., "America/New_York")
    #[serde(default)]
    pub timezone: Option<String>,

    /// Locale (e.g., "en-US")
    #[serde(default)]
    pub locale: Option<String>,

    /// Hardware concurrency (CPU cores to report)
    #[serde(default)]
    pub hardware_concurrency: Option<u32>,

    /// Device memory in GB
    #[serde(default)]
    pub device_memory: Option<u32>,

    /// The raw fingerprint JSON blob (generated by engine's fingerprint generator)
    #[serde(default)]
    pub raw_fingerprint: Option<String>,

    /// Whether to randomize fingerprint on each launch
    #[serde(default)]
    pub randomize_on_launch: bool,
}

// ─── Browser Profile ───────────────────────────────────────────────

/// A browser profile with isolated identity, cookies, storage, and fingerprint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShieldProfile {
    pub id: String,
    pub name: String,
    pub engine: BrowserEngine,
    pub engine_version: String,

    #[serde(default)]
    pub proxy: Option<ProxyConfig>,

    #[serde(default)]
    pub fingerprint: FingerprintConfig,

    #[serde(default)]
    pub tags: Vec<String>,

    #[serde(default)]
    pub note: Option<String>,

    /// PID of the running browser process (None if not running)
    #[serde(default)]
    pub process_id: Option<u32>,

    /// Epoch timestamp of last launch
    #[serde(default)]
    pub last_launch: Option<u64>,

    /// Epoch timestamp of creation
    pub created_at: u64,
}

impl ShieldProfile {
    /// Create a new profile with a generated UUID.
    pub fn new(name: String, engine: BrowserEngine, engine_version: String) -> Self {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        Self {
            id: uuid::Uuid::new_v4().to_string(),
            name,
            engine,
            engine_version,
            proxy: None,
            fingerprint: FingerprintConfig::default(),
            tags: Vec::new(),
            note: None,
            process_id: None,
            last_launch: None,
            created_at: now,
        }
    }

    /// Get the profile data directory path: {profiles_dir}/{id}/profile
    pub fn data_dir(&self, profiles_dir: &Path) -> PathBuf {
        profiles_dir.join(&self.id).join("profile")
    }

    /// Get the metadata file path: {profiles_dir}/{id}/metadata.json
    pub fn metadata_path(&self, profiles_dir: &Path) -> PathBuf {
        profiles_dir.join(&self.id).join("metadata.json")
    }

    pub fn is_running(&self) -> bool {
        self.process_id.is_some()
    }
}

// ─── Profile Manager ───────────────────────────────────────────────

/// Manages shield browser profiles on disk.
pub struct ProfileManager {
    profiles_dir: PathBuf,
}

impl ProfileManager {
    pub fn new(base_dir: &Path) -> Self {
        Self {
            profiles_dir: base_dir.join("shield-profiles"),
        }
    }

    pub fn profiles_dir(&self) -> &Path {
        &self.profiles_dir
    }

    /// Create a new profile and persist it to disk.
    pub fn create_profile(&self, profile: &ShieldProfile) -> Result<()> {
        let profile_dir = self.profiles_dir.join(&profile.id);
        let data_dir = profile_dir.join("profile");
        let metadata_path = profile_dir.join("metadata.json");

        // Check for duplicate name (case-insensitive)
        let existing = self.list_profiles()?;
        if existing
            .iter()
            .any(|p| p.name.to_lowercase() == profile.name.to_lowercase())
        {
            anyhow::bail!("Profile with name '{}' already exists", profile.name);
        }

        fs::create_dir_all(&data_dir).context("Failed to create profile data directory")?;

        let json = serde_json::to_string_pretty(profile).context("Failed to serialize profile")?;
        fs::write(&metadata_path, json).context("Failed to write profile metadata")?;

        Ok(())
    }

    /// List all profiles from disk.
    pub fn list_profiles(&self) -> Result<Vec<ShieldProfile>> {
        if !self.profiles_dir.exists() {
            return Ok(Vec::new());
        }

        let mut profiles = Vec::new();
        for entry in
            fs::read_dir(&self.profiles_dir).context("Failed to read profiles directory")?
        {
            let entry = entry?;
            let path = entry.path();

            if path.is_dir() {
                let metadata_file = path.join("metadata.json");
                if metadata_file.exists() {
                    let content = fs::read_to_string(&metadata_file)
                        .with_context(|| format!("Failed to read {}", metadata_file.display()))?;
                    let profile: ShieldProfile = serde_json::from_str(&content)
                        .with_context(|| format!("Failed to parse {}", metadata_file.display()))?;
                    profiles.push(profile);
                }
            }
        }

        Ok(profiles)
    }

    /// Get a profile by ID.
    pub fn get_profile(&self, id: &str) -> Result<ShieldProfile> {
        let metadata_path = self.profiles_dir.join(id).join("metadata.json");
        let content = fs::read_to_string(&metadata_path)
            .with_context(|| format!("Profile '{id}' not found"))?;
        let profile: ShieldProfile =
            serde_json::from_str(&content).context("Failed to parse profile metadata")?;
        Ok(profile)
    }

    /// Update a profile on disk.
    pub fn update_profile(&self, profile: &ShieldProfile) -> Result<()> {
        let metadata_path = self.profiles_dir.join(&profile.id).join("metadata.json");
        if !metadata_path.exists() {
            anyhow::bail!("Profile '{}' not found", profile.id);
        }

        let json = serde_json::to_string_pretty(profile).context("Failed to serialize profile")?;
        fs::write(&metadata_path, json).context("Failed to write profile metadata")?;
        Ok(())
    }

    /// Delete a profile (directory and all data).
    pub fn delete_profile(&self, id: &str) -> Result<()> {
        let profile_dir = self.profiles_dir.join(id);
        if !profile_dir.exists() {
            anyhow::bail!("Profile '{id}' not found");
        }

        // Check if browser is running
        let profile = self.get_profile(id)?;
        if profile.is_running() {
            anyhow::bail!("Cannot delete profile while browser is running. Stop it first.");
        }

        fs::remove_dir_all(&profile_dir).with_context(|| {
            format!(
                "Failed to delete profile directory: {}",
                profile_dir.display()
            )
        })?;
        Ok(())
    }

    /// Rename a profile.
    pub fn rename_profile(&self, id: &str, new_name: &str) -> Result<ShieldProfile> {
        // Check duplicate
        let existing = self.list_profiles()?;
        if existing
            .iter()
            .any(|p| p.name.to_lowercase() == new_name.to_lowercase())
        {
            anyhow::bail!("Profile with name '{new_name}' already exists");
        }

        let mut profile = self.get_profile(id)?;
        profile.name = new_name.to_string();
        self.update_profile(&profile)?;
        Ok(profile)
    }

    /// Record that a browser process started for a profile.
    pub fn set_running(&self, id: &str, pid: u32) -> Result<()> {
        let mut profile = self.get_profile(id)?;
        profile.process_id = Some(pid);
        profile.last_launch = Some(
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs(),
        );
        self.update_profile(&profile)
    }

    /// Record that a browser process stopped for a profile.
    pub fn set_stopped(&self, id: &str) -> Result<()> {
        let mut profile = self.get_profile(id)?;
        profile.process_id = None;
        self.update_profile(&profile)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn test_manager() -> (ProfileManager, TempDir) {
        let tmp = TempDir::new().unwrap();
        let mgr = ProfileManager::new(tmp.path());
        (mgr, tmp)
    }

    #[test]
    fn test_create_and_list_profiles() {
        let (mgr, _tmp) = test_manager();

        let profile = ShieldProfile::new(
            "Test Profile".into(),
            BrowserEngine::Wayfern,
            "133.0.0".into(),
        );
        mgr.create_profile(&profile).unwrap();

        let profiles = mgr.list_profiles().unwrap();
        assert_eq!(profiles.len(), 1);
        assert_eq!(profiles[0].name, "Test Profile");
        assert_eq!(profiles[0].engine, BrowserEngine::Wayfern);
    }

    #[test]
    fn test_duplicate_name_rejected() {
        let (mgr, _tmp) = test_manager();

        let p1 = ShieldProfile::new("Alpha".into(), BrowserEngine::Wayfern, "1.0".into());
        mgr.create_profile(&p1).unwrap();

        let p2 = ShieldProfile::new("alpha".into(), BrowserEngine::Camoufox, "2.0".into());
        assert!(mgr.create_profile(&p2).is_err());
    }

    #[test]
    fn test_delete_profile() {
        let (mgr, _tmp) = test_manager();

        let profile = ShieldProfile::new("Deletable".into(), BrowserEngine::Camoufox, "1.0".into());
        let id = profile.id.clone();
        mgr.create_profile(&profile).unwrap();

        mgr.delete_profile(&id).unwrap();
        assert!(mgr.list_profiles().unwrap().is_empty());
    }

    #[test]
    fn test_rename_profile() {
        let (mgr, _tmp) = test_manager();

        let profile = ShieldProfile::new("Original".into(), BrowserEngine::Wayfern, "1.0".into());
        let id = profile.id.clone();
        mgr.create_profile(&profile).unwrap();

        let renamed = mgr.rename_profile(&id, "Renamed").unwrap();
        assert_eq!(renamed.name, "Renamed");

        let fetched = mgr.get_profile(&id).unwrap();
        assert_eq!(fetched.name, "Renamed");
    }

    #[test]
    fn test_set_running_and_stopped() {
        let (mgr, _tmp) = test_manager();

        let profile = ShieldProfile::new("Runner".into(), BrowserEngine::Wayfern, "1.0".into());
        let id = profile.id.clone();
        mgr.create_profile(&profile).unwrap();

        mgr.set_running(&id, 12345).unwrap();
        let p = mgr.get_profile(&id).unwrap();
        assert_eq!(p.process_id, Some(12345));
        assert!(p.last_launch.is_some());

        mgr.set_stopped(&id).unwrap();
        let p = mgr.get_profile(&id).unwrap();
        assert_eq!(p.process_id, None);
    }

    #[test]
    fn test_cannot_delete_running_profile() {
        let (mgr, _tmp) = test_manager();

        let profile = ShieldProfile::new("Running".into(), BrowserEngine::Wayfern, "1.0".into());
        let id = profile.id.clone();
        mgr.create_profile(&profile).unwrap();
        mgr.set_running(&id, 999).unwrap();

        assert!(mgr.delete_profile(&id).is_err());
    }

    #[test]
    fn test_fingerprint_serialization() {
        let fp = FingerprintConfig {
            os: Some("windows".into()),
            user_agent: Some("Mozilla/5.0 (Windows NT 10.0; Win64; x64)".into()),
            screen: Some([1920, 1080]),
            webgl_vendor: Some("Google Inc. (NVIDIA)".into()),
            webgl_renderer: Some("ANGLE (NVIDIA, GeForce RTX 3080)".into()),
            timezone: Some("America/New_York".into()),
            locale: Some("en-US".into()),
            hardware_concurrency: Some(16),
            device_memory: Some(32),
            raw_fingerprint: None,
            randomize_on_launch: false,
        };

        let json = serde_json::to_string(&fp).unwrap();
        let parsed: FingerprintConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.os.unwrap(), "windows");
        assert_eq!(parsed.screen.unwrap(), [1920, 1080]);
    }
}
