/**
 * Figma JSON Render Schema
 *
 * A declarative JSON format that maps 1:1 to Figma's node tree.
 * Can be authored manually, exported from Figma REST API via the converter,
 * or auto-generated by an LLM agent.
 */

// ─── Primitive value types ───────────────────────────────────────────

export type FColor = {
  r: number; // 0–1
  g: number; // 0–1
  b: number; // 0–1
  a: number; // 0–1
};

export type FGradientStop = {
  position: number; // 0–1
  color: FColor;
};

export type FFill =
  | { type: "SOLID"; color: FColor; opacity?: number }
  | { type: "LINEAR_GRADIENT"; stops: FGradientStop[]; angle?: number }
  | { type: "RADIAL_GRADIENT"; stops: FGradientStop[] }
  | { type: "IMAGE"; src: string; scaleMode?: "FILL" | "FIT" | "CROP" | "TILE" }
  ;

export type FStroke = {
  color: FColor;
  weight: number;
  align?: "INSIDE" | "OUTSIDE" | "CENTER";
  dashPattern?: number[];
};

export type FShadow = {
  type: "DROP_SHADOW" | "INNER_SHADOW";
  color: FColor;
  offset: { x: number; y: number };
  radius: number;
  spread?: number;
};

export type FBlur = {
  type: "LAYER" | "BACKGROUND";
  radius: number;
};

export type FConstraint = {
  horizontal: "LEFT" | "RIGHT" | "CENTER" | "STRETCH" | "SCALE";
  vertical: "TOP" | "BOTTOM" | "CENTER" | "STRETCH" | "SCALE";
};

export type FLayoutMode = "NONE" | "HORIZONTAL" | "VERTICAL";

export type FLayoutAlign = "MIN" | "CENTER" | "MAX" | "STRETCH" | "BASELINE";

export type FLayoutSizing = "FIXED" | "HUG" | "FILL";

export type FTextDecoration = "NONE" | "UNDERLINE" | "STRIKETHROUGH";

export type FTextCase = "ORIGINAL" | "UPPER" | "LOWER" | "TITLE";

export type FTextAlignHorizontal = "LEFT" | "CENTER" | "RIGHT" | "JUSTIFIED";

export type FTextAlignVertical = "TOP" | "CENTER" | "BOTTOM";

// ─── Node types ──────────────────────────────────────────────────────

export type FBaseNode = {
  /** Unique node ID (from Figma or generated) */
  id: string;
  /** Display name — visible in layer panel */
  name: string;
  /** Relative X coordinate from parent (used for interactive dragging) */
  x?: number;
  /** Relative Y coordinate from parent (used for interactive dragging) */
  y?: number;
  /** Whether this node is visible */
  visible?: boolean; // default true
  /** Opacity 0–1 */
  opacity?: number; // default 1
  /** Rotation in degrees */
  rotation?: number;
  /** Border radius (uniform or per-corner) */
  borderRadius?: number | [number, number, number, number];
  /** Clip content to frame bounds */
  clipsContent?: boolean;
  /** CSS blend mode */
  blendMode?: string;
  /** Fills */
  fills?: FFill[];
  /** Strokes */
  strokes?: FStroke[];
  /** Effects: shadows + blurs */
  effects?: (FShadow | FBlur)[];
  /** Constraints for absolute positioning */
  constraints?: FConstraint;
  /** Interaction: click handler ID for the renderer to wire up */
  onClick?: string;
  /** Arbitrary data the LLM or designer can attach */
  meta?: Record<string, unknown>;
};

export type FFrameNode = FBaseNode & {
  type: "FRAME" | "GROUP" | "COMPONENT" | "INSTANCE";
  /** Absolute dimensions (from Figma) */
  width?: number;
  height?: number;
  /** Auto-layout */
  layoutMode?: FLayoutMode;
  layoutWrap?: "NO_WRAP" | "WRAP";
  primaryAxisAlignItems?: FLayoutAlign;
  counterAxisAlignItems?: FLayoutAlign;
  primaryAxisSizingMode?: FLayoutSizing;
  counterAxisSizingMode?: FLayoutSizing;
  layoutGrow?: number;
  /** Spacing */
  itemSpacing?: number;
  counterAxisSpacing?: number;
  paddingLeft?: number;
  paddingRight?: number;
  paddingTop?: number;
  paddingBottom?: number;
  /** Children */
  children?: FNode[];
};

export type FTextNode = FBaseNode & {
  type: "TEXT";
  /** The text content */
  characters: string;
  /** Font */
  fontFamily?: string;
  fontWeight?: number;
  fontSize?: number;
  lineHeight?: number | "AUTO";
  letterSpacing?: number;
  textDecoration?: FTextDecoration;
  textCase?: FTextCase;
  textAlignHorizontal?: FTextAlignHorizontal;
  textAlignVertical?: FTextAlignVertical;
  /** Max width before wrapping */
  width?: number;
};

export type FRectangleNode = FBaseNode & {
  type: "RECTANGLE";
  width: number;
  height: number;
};

export type FEllipseNode = FBaseNode & {
  type: "ELLIPSE";
  width: number;
  height: number;
};

export type FVectorNode = FBaseNode & {
  type: "VECTOR" | "LINE" | "STAR" | "POLYGON";
  width: number;
  height: number;
  /** Optional SVG path data for complex vectors */
  svgPath?: string;
};

export type FImageNode = FBaseNode & {
  type: "IMAGE";
  width: number;
  height: number;
  src: string;
  alt?: string;
  objectFit?: "cover" | "contain" | "fill" | "none";
};

export type FNode =
  | FFrameNode
  | FTextNode
  | FRectangleNode
  | FEllipseNode
  | FVectorNode
  | FImageNode;

// ─── Document root ───────────────────────────────────────────────────

export type FDocument = {
  /** Schema version for forward compat */
  version: "1.0";
  /** Document name */
  name: string;
  /** Canvas width / height (optional, used for preview sizing) */
  width?: number;
  height?: number;
  /** Background color of the canvas */
  background?: FColor;
  /** The root node tree */
  children: FNode[];
  /** Metadata: Figma file key, page name, export date, etc. */
  meta?: {
    figmaFileKey?: string;
    figmaNodeId?: string;
    exportedAt?: string;
    generator?: "figma-api" | "llm-agent" | "manual";
    [key: string]: unknown;
  };
};
